#!/usr/bin/env python
import socket
import paramiko
import os
import sys
import threading

CWD = os.path.dirname(os.path.relpath(__file__))
HOSTKEY = paramiko.RSAKey(filename=os.path.join(CWD, 'test_rsa.key'))

class Server(paramiko.ServerInterface):
    def __init__(self):
        self.event = threading.Event()

    def check_channel_request(self, kind, chanid):
        if kind == 'session':
            return paramiko.OPEN_SUCCEEDED
        return paramiko.OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED

    def check_auth_password(self, username, password):
        if username == 'leroy' and password == 'test':
            return paramiko.AUTH_SUCCESSFUL

if __name__ == '__main__':
    ssh_host = '127.0.0.1'
    ssh_port = 2222
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind((ssh_host, ssh_port))
        sock.listen(100)
        print('[+] Listening for connection...')
        client, address = sock.accept()
    except Exception as e:
        print('[-] Listen failed: ' + str(e))
        sys.exit()
    else:
        print('[+] Got a connection!', client, address)

    bhSession = paramiko.Transport(client)
    bhSession.add_server_key(HOSTKEY)
    server = Server()
    bhSession.start_server(server=server)

    chan = bhSession.accept(20)
    if chan is None:
        print('*** No channel')
        sys.exit()

    print('[+] Authenticated')
    print(chan.recv(1024))
    chan.send('Welcome to bh_ssh')
    try:
        while True:
            command = input('Enter command: ')
            if command != 'exit':
                chan.send(command)
                r = chan.recv(8192)
                print(r.decode())
            else:
                chan.send('exit')
                print('exiting')
                bhSession.close()
                break
    except KeyboardInterrupt as e:
        print('[-] Session closed')
        bhSession.close()
