#!/usr/bin/env python
import socket

target_host = '127.0.0.1'
target_port = 9000

def send(client):
    client.connect((target_host, target_port))
    client.send(b"GET / HTTP/1.1\r\nHost: cn.bing.com\r\n\r\n")
    response = client.recv(4096)
    print(response)
    client.close()

if __name__ == '__main__':
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    send(client=client)
